### PR TITLE
Bug/use environment variable

### PR DESCRIPTION
**Pull request by chloe2407**
**Main Changes**
For this PR, I focused on removing the dependency on using `config.ini` file and instead created a `.env` file for handling configurations. We are making this transition as it eases deployment in AWS ECS and `.env` files are quite standard for configuring applications in many modern development environments.

In `.env`, I translated each configuration value specified in  `sample_config.ini` to the new `.env` file as an environment variable, following the UPPERCASE_WITH_UNDERSCORES format (e.g. `WORKBENCH_HOST`).

**Setup Instructions**
Before running, we need to run `pip install python-dotenv` in your virtual environment (venv). Note: You can also try to run `pip install -r requirements.txt` as I added `python-dotenv` on line 43 of `requirements.txt`. You will also need to create a new `.env` file in the root directory. Please refer to `sample_.env` for the environment variable names and fill in the blanks similar to the current `config.ini`.

**Configuring Host and Port**
For host and port configuration, we have 3 different methods we can specify it through CLI or .env file. If it is not specified, the default host is '0.0.0.0' and default port is '8050'.

- .env: Enter in the host and port values in the .env file as needed.
- CLI: 
    - within the PowerShell session: We can optionally drop either line if we don't want to specify a host or port.
`>> $env:WORKBENCH_HOST = "<host>"`
`>> $env:WORKBENCH_PORT = "<port>"`
   - during the execution of the Python script:  We can optionally drop the `--host <host>` or `--port <port>`.
`python app/dash_app.py --host <host> --port <port>`.

### CODE REVIEW

**Review by trbeattie — CHANGES_REQUESTED** [review]
This is a good start. Handling of environment variables in `dash_app.py` looks good. However, we'll want to make sure that the app runs successfully without depending on `config.ini` in any file. All files under `app` and under `scripts` which make use of the `configparser` module will need to be refactored to use `os.getenv()` calls (and `load_dotenv()` where necessary in scripts) instead. All instances of `import configparser` should be removed. To test, make sure that you can run `python app/dash_app.py` and any scripts currently using `configparser` with these changes and without there being a `config.ini` file present in the project root.

The README also makes reference to `config.ini`, so it should be updated to reflect the switch to `.env` instead.

**Review by trbeattie — CHANGES_REQUESTED** [review]
This is really impressive work. I like how you've refactored things and handled centralizing the configuration. Seems to run fine for me via the Python interpreter. 

One thing I forgot to list in my initial requirements for this PR is making sure that the docker build for this app also succeeds. I think it might be as simple as deleting line 6 of the `Dockerfile` to get that working. If you could do that and test building and running the Dockerized version of the app before we finalize this PR, that would be appreciated. You can find sample build and run commands in `runDocker.sh`.

Might also be a good idea to test running any scripts you've modified in the `scripts` directory if you have not already. I don't know much those scripts so I would recommend talking to Drew if you have any questions about how to run and test them.

**Comment by chloe2407** [comment]
I have made some changes that @trbeattie mentioned above.



In this new version, I went through files located in the `app` and `scripts` folder and removed any mentions of `config.ini`, `configparser`, etc. I also updated the first section of the README file to replace mentions of `config.ini` with `.env`.


**Reorganization of Files**
Additionally, I moved any helper functions located in `overview.py` and `site.py` into `data_utils.py`. This is so that we can reuse any repeated functions and also use of os.getenv() and load_dotenv() calls can be centralized in one file in `data_utils.py`. I have also reorganized the helper functions in `data_utils.py` by type (e.g. retrieve data from an API, calculations, visualization, etc.)


**Improving Redundancy**
I also created a file `global_variables.py` that stores any global variable, which we can reference in various files. For example, the basemap configuration variables (`BASEMAP_NAME`, `BASEMAP_ATTRIBUTION`, `BASEMAP_URL`) are utilized in both `overview.py` and `site.py` with the same values.

**Automation**
I also modified the Dockerfile by removing `COPY ./config.ini /config.ini`. There is a new file `docker-compose.yml` that will help with container building functionality. 
1. Paste in the AWS environment variables
2. Build the image: `docker build -t volc_interp_wb .`
3. Run the container: `docker-compose up`

**Future**
I added a `data_utils.py` file within the scripts folder. We will need to test out running this, as I am not sure yet if it is running correctly.

**Comment by chloe2407** [comment]
After testing out the scripts, most seem to be working fine, though @drotheram should test it on his side before merging into main.

**Outstanding Issues**
- `calc_avg_coh.py` hasn't been tested yet as I am unable to install osgeo or gdal without admin assistance.
- `get_latest_baselines.py` occasionally outputs 'File not found'.
- `gen_avg_coh_matrix.py` has index out of range errors. Drew mentioned this script might be there by accident.

**Modifications**
- in `load_updated_coherence_matrix.py`, I commented out line 38, replacing it with a new line on line 39 (`Filename=f'Data{args.site}{args.beam}CoherenceMatrix.csv'`) as it was interpreting the wrong directory before.

**Future**
As we are moving away from using geoserver, it is possible the scripts `geoserverLocalREST.sh` and `geoserverREST.sh` may no longer be needed.

**Comment by drotheram** [comment]
Overall, great work! A few changes before we are ready to merge but we are almost there:

1. 
> Outstanding Issues
> 
> get_latest_baselines.py occasionally outputs 'File not found'. 

This is expected behavior, just means that the beams present in `beams.yml` have not been processed. No action required.

2. 
> Modifications
> 
> in load_updated_coherence_matrix.py, I commented out line 38, replacing it with a new line on line 39 (Filename=f'Data{args.site}{args.beam}CoherenceMatrix.csv') as it was interpreting the wrong directory before.

This should potentially use `os.path.join()` instead since we want to send these files to a subdirectory rather than a long string with a prefix. The way it was written previously would not work in Windows with `\` directory delimiters

3. geoserverLocalREST.sh and geoserverREST.sh can be removed. So can downoloadEODMSData.sh

4. sample_config.ini can be removed as a file and from the gitignore

**Review by drotheram — APPROVED** [review]
Nicely done, approved

**Review by drotheram — APPROVED** [review]

**Review by trbeattie — APPROVED** [review]

**Pull request merged**
